pub type MessageType = u8;
pub const SOLICIT: MessageType = 1;	// [RFC8415]
pub const ADVERTISE: MessageType = 2;	// [RFC8415]
pub const REQUEST: MessageType = 3;	// [RFC8415]
pub const CONFIRM: MessageType = 4;	// [RFC8415]
pub const RENEW: MessageType = 5;	// [RFC8415]
pub const REBIND: MessageType = 6;	// [RFC8415]
pub const REPLY: MessageType = 7;	// [RFC8415]
pub const RELEASE: MessageType = 8;	// [RFC8415]
pub const DECLINE: MessageType = 9;	// [RFC8415]
pub const RECONFIGURE: MessageType = 10;	// [RFC8415]
pub const INFORMATION_REQUEST: MessageType = 11;	// [RFC8415]
pub const RELAY_FORW: MessageType = 12;	// [RFC8415]
pub const RELAY_REPL: MessageType = 13;	// [RFC8415]
pub const LEASEQUERY: MessageType = 14;	// [RFC5007]
pub const LEASEQUERY_REPLY: MessageType = 15;	// [RFC5007]
pub const LEASEQUERY_DONE: MessageType = 16;	// [RFC5460]
pub const LEASEQUERY_DATA: MessageType = 17;	// [RFC5460]
pub const RECONFIGURE_REQUEST: MessageType = 18;	// [RFC6977]
pub const RECONFIGURE_REPLY: MessageType = 19;	// [RFC6977]
pub const DHCPV4_QUERY: MessageType = 20;	// [RFC7341]
pub const DHCPV4_RESPONSE: MessageType = 21;	// [RFC7341]
pub const ACTIVELEASEQUERY: MessageType = 22;	// [RFC7653]
pub const STARTTLS: MessageType = 23;	// [RFC7653]
pub const BNDUPD: MessageType = 24;	// [RFC8156]
pub const BNDREPLY: MessageType = 25;	// [RFC8156]
pub const POOLREQ: MessageType = 26;	// [RFC8156]
pub const POOLRESP: MessageType = 27;	// [RFC8156]
pub const UPDREQ: MessageType = 28;	// [RFC8156]
pub const UPDREQALL: MessageType = 29;	// [RFC8156]
pub const UPDDONE: MessageType = 30;	// [RFC8156]
pub const CONNECT: MessageType = 31;	// [RFC8156]
pub const CONNECTREPLY: MessageType = 32;	// [RFC8156]
pub const DISCONNECT: MessageType = 33;	// [RFC8156]
pub const STATE: MessageType = 34;	// [RFC8156]
pub const CONTACT: MessageType = 35;	// [RFC8156]

pub fn to_str(a: MessageType) -> Result<&'static str, ()> {
  match a {
    1 => Ok("SOLICIT"),
    2 => Ok("ADVERTISE"),
    3 => Ok("REQUEST"),
    4 => Ok("CONFIRM"),
    5 => Ok("RENEW"),
    6 => Ok("REBIND"),
    7 => Ok("REPLY"),
    8 => Ok("RELEASE"),
    9 => Ok("DECLINE"),
    10 => Ok("RECONFIGURE"),
    11 => Ok("INFORMATION_REQUEST"),
    12 => Ok("RELAY_FORW"),
    13 => Ok("RELAY_REPL"),
    14 => Ok("LEASEQUERY"),
    15 => Ok("LEASEQUERY_REPLY"),
    16 => Ok("LEASEQUERY_DONE"),
    17 => Ok("LEASEQUERY_DATA"),
    18 => Ok("RECONFIGURE_REQUEST"),
    19 => Ok("RECONFIGURE_REPLY"),
    20 => Ok("DHCPV4_QUERY"),
    21 => Ok("DHCPV4_RESPONSE"),
    22 => Ok("ACTIVELEASEQUERY"),
    23 => Ok("STARTTLS"),
    24 => Ok("BNDUPD"),
    25 => Ok("BNDREPLY"),
    26 => Ok("POOLREQ"),
    27 => Ok("POOLRESP"),
    28 => Ok("UPDREQ"),
    29 => Ok("UPDREQALL"),
    30 => Ok("UPDDONE"),
    31 => Ok("CONNECT"),
    32 => Ok("CONNECTREPLY"),
    33 => Ok("DISCONNECT"),
    34 => Ok("STATE"),
    35 => Ok("CONTACT"),
    _ => Err(()),
  }
}
