pub type OptionCode = u16;
pub const OPTION_CLIENTID: OptionCode = 1;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_SERVERID: OptionCode = 2;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_IA_NA: OptionCode = 3;	// [RFC8415], ORO: No, SINGLETON: No
pub const OPTION_IA_TA: OptionCode = 4;	// [RFC8415], ORO: No, SINGLETON: No
pub const OPTION_IAADDR: OptionCode = 5;	// [RFC8415], ORO: No, SINGLETON: No
pub const OPTION_ORO: OptionCode = 6;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_PREFERENCE: OptionCode = 7;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_ELAPSED_TIME: OptionCode = 8;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_RELAY_MSG: OptionCode = 9;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_AUTH: OptionCode = 11;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_UNICAST: OptionCode = 12;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_STATUS_CODE: OptionCode = 13;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_RAPID_COMMIT: OptionCode = 14;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_USER_CLASS: OptionCode = 15;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_VENDOR_CLASS: OptionCode = 16;	// [RFC8415], ORO: No, SINGLETON: No[1]
pub const OPTION_VENDOR_OPTS: OptionCode = 17;	// [RFC8415], ORO: Optional, SINGLETON: No[1]
pub const OPTION_INTERFACE_ID: OptionCode = 18;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_RECONF_MSG: OptionCode = 19;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_RECONF_ACCEPT: OptionCode = 20;	// [RFC8415], ORO: No, SINGLETON: Yes
pub const OPTION_SIP_SERVER_D: OptionCode = 21;	// [RFC3319], ORO: Yes, SINGLETON: Yes
pub const OPTION_SIP_SERVER_A: OptionCode = 22;	// [RFC3319], ORO: Yes, SINGLETON: Yes
pub const OPTION_DNS_SERVERS: OptionCode = 23;	// [RFC3646], ORO: Yes, SINGLETON: Yes
pub const OPTION_DOMAIN_LIST: OptionCode = 24;	// [RFC3646], ORO: Yes, SINGLETON: Yes
pub const OPTION_IA_PD: OptionCode = 25;	// [RFC3633][RFC8415], ORO: No, SINGLETON: No
pub const OPTION_IAPREFIX: OptionCode = 26;	// [RFC3633][RFC8415], ORO: No, SINGLETON: No
pub const OPTION_NIS_SERVERS: OptionCode = 27;	// [RFC3898], ORO: Yes, SINGLETON: Yes
pub const OPTION_NISP_SERVERS: OptionCode = 28;	// [RFC3898], ORO: Yes, SINGLETON: Yes
pub const OPTION_NIS_DOMAIN_NAME: OptionCode = 29;	// [RFC3898], ORO: Yes, SINGLETON: Yes
pub const OPTION_NISP_DOMAIN_NAME: OptionCode = 30;	// [RFC3898], ORO: Yes, SINGLETON: Yes
pub const OPTION_SNTP_SERVERS: OptionCode = 31;	// [RFC4075], ORO: Yes, SINGLETON: Yes
pub const OPTION_INFORMATION_REFRESH_TIME: OptionCode = 32;	// [RFC4242][RFC8415], ORO: Required for Information-request, SINGLETON: Yes
pub const OPTION_BCMCS_SERVER_D: OptionCode = 33;	// [RFC4280], ORO: Yes, SINGLETON: Yes
pub const OPTION_BCMCS_SERVER_A: OptionCode = 34;	// [RFC4280], ORO: Yes, SINGLETON: Yes
pub const OPTION_GEOCONF_CIVIC: OptionCode = 36;	// [RFC4776], ORO: Yes, SINGLETON: Yes
pub const OPTION_REMOTE_ID: OptionCode = 37;	// [RFC4649], ORO: No, SINGLETON: Yes
pub const OPTION_SUBSCRIBER_ID: OptionCode = 38;	// [RFC4580], ORO: No, SINGLETON: Yes
pub const OPTION_CLIENT_FQDN: OptionCode = 39;	// [RFC4704], ORO: Yes, SINGLETON: Yes
pub const OPTION_PANA_AGENT: OptionCode = 40;	// [RFC5192], ORO: Yes, SINGLETON: Yes
pub const OPTION_NEW_POSIX_TIMEZONE: OptionCode = 41;	// [RFC4833], ORO: Yes, SINGLETON: Yes
pub const OPTION_NEW_TZDB_TIMEZONE: OptionCode = 42;	// [RFC4833], ORO: Yes, SINGLETON: Yes
pub const OPTION_ERO: OptionCode = 43;	// [RFC4994], ORO: No, SINGLETON: Yes
pub const OPTION_LQ_QUERY: OptionCode = 44;	// [RFC5007], ORO: No, SINGLETON: Yes
pub const OPTION_CLIENT_DATA: OptionCode = 45;	// [RFC5007], ORO: No, SINGLETON: Yes
pub const OPTION_CLT_TIME: OptionCode = 46;	// [RFC5007], ORO: No, SINGLETON: Yes
pub const OPTION_LQ_RELAY_DATA: OptionCode = 47;	// [RFC5007], ORO: No, SINGLETON: Yes
pub const OPTION_LQ_CLIENT_LINK: OptionCode = 48;	// [RFC5007], ORO: No, SINGLETON: Yes
pub const OPTION_MIP6_HNIDF: OptionCode = 49;	// [RFC6610], ORO: Yes, SINGLETON: Yes
pub const OPTION_MIP6_VDINF: OptionCode = 50;	// [RFC6610], ORO: Yes, SINGLETON: Yes
pub const OPTION_V6_LOST: OptionCode = 51;	// [RFC5223], ORO: Yes, SINGLETON: Yes
pub const OPTION_CAPWAP_AC_V6: OptionCode = 52;	// [RFC5417], ORO: Yes, SINGLETON: Yes
pub const OPTION_RELAY_ID: OptionCode = 53;	// [RFC5460], ORO: No, SINGLETON: Yes
pub const OPTION_IPV6_ADDRESS_MOS: OptionCode = 54;	// [RFC5678], ORO: Yes, SINGLETON: Yes
pub const OPTION_IPV6_FQDN_MOS: OptionCode = 55;	// [RFC5678], ORO: Yes, SINGLETON: Yes
pub const OPTION_NTP_SERVER: OptionCode = 56;	// [RFC5908], ORO: Yes, SINGLETON: Yes
pub const OPTION_V6_ACCESS_DOMAIN: OptionCode = 57;	// [RFC5986], ORO: Yes, SINGLETON: Yes
pub const OPTION_SIP_UA_CS_LIST: OptionCode = 58;	// [RFC6011], ORO: Yes, SINGLETON: Yes
pub const OPT_BOOTFILE_URL: OptionCode = 59;	// [RFC5970], ORO: Yes, SINGLETON: Yes
pub const OPT_BOOTFILE_PARAM: OptionCode = 60;	// [RFC5970], ORO: Yes, SINGLETON: Yes
pub const OPTION_CLIENT_ARCH_TYPE: OptionCode = 61;	// [RFC5970], ORO: No, SINGLETON: Yes
pub const OPTION_NII: OptionCode = 62;	// [RFC5970], ORO: Yes, SINGLETON: Yes
pub const OPTION_GEOLOCATION: OptionCode = 63;	// [RFC6225], ORO: Yes, SINGLETON: Yes
pub const OPTION_AFTR_NAME: OptionCode = 64;	// [RFC6334], ORO: Yes, SINGLETON: Yes
pub const OPTION_ERP_LOCAL_DOMAIN_NAME: OptionCode = 65;	// [RFC6440], ORO: Yes, SINGLETON: Yes
pub const OPTION_RSOO: OptionCode = 66;	// [RFC6422], ORO: No, SINGLETON: Yes
pub const OPTION_PD_EXCLUDE: OptionCode = 67;	// [RFC6603], ORO: Yes, SINGLETON: Yes
pub const OPTION_VSS: OptionCode = 68;	// [RFC6607], ORO: No, SINGLETON: Yes
pub const OPTION_MIP6_IDINF: OptionCode = 69;	// [RFC6610], ORO: Yes, SINGLETON: Yes
pub const OPTION_MIP6_UDINF: OptionCode = 70;	// [RFC6610], ORO: Yes, SINGLETON: Yes
pub const OPTION_MIP6_HNP: OptionCode = 71;	// [RFC6610], ORO: Yes, SINGLETON: Yes
pub const OPTION_MIP6_HAA: OptionCode = 72;	// [RFC6610], ORO: Yes, SINGLETON: Yes
pub const OPTION_MIP6_HAF: OptionCode = 73;	// [RFC6610], ORO: Yes, SINGLETON: Yes
pub const OPTION_RDNSS_SELECTION: OptionCode = 74;	// [RFC6731], ORO: Yes, SINGLETON: Yes
pub const OPTION_KRB_PRINCIPAL_NAME: OptionCode = 75;	// [RFC6784], ORO: Yes, SINGLETON: Yes
pub const OPTION_KRB_REALM_NAME: OptionCode = 76;	// [RFC6784], ORO: Yes, SINGLETON: Yes
pub const OPTION_KRB_DEFAULT_REALM_NAME: OptionCode = 77;	// [RFC6784], ORO: Yes, SINGLETON: Yes
pub const OPTION_KRB_KDC: OptionCode = 78;	// [RFC6784], ORO: Yes, SINGLETON: Yes
pub const OPTION_CLIENT_LINKLAYER_ADDR: OptionCode = 79;	// [RFC6939], ORO: No, SINGLETON: Yes
pub const OPTION_LINK_ADDRESS: OptionCode = 80;	// [RFC6977], ORO: No, SINGLETON: Yes
pub const OPTION_RADIUS: OptionCode = 81;	// [RFC7037], ORO: No, SINGLETON: Yes
pub const OPTION_SOL_MAX_RT: OptionCode = 82;	// [RFC7083][RFC8415], ORO: Required for Solicit, SINGLETON: Yes
pub const OPTION_INF_MAX_RT: OptionCode = 83;	// [RFC7083][RFC8415], ORO: Required for Information-request, SINGLETON: Yes
pub const OPTION_ADDRSEL: OptionCode = 84;	// [RFC7078], ORO: Yes, SINGLETON: Yes
pub const OPTION_ADDRSEL_TABLE: OptionCode = 85;	// [RFC7078], ORO: Yes, SINGLETON: Yes
pub const OPTION_V6_PCP_SERVER: OptionCode = 86;	// [RFC7291], ORO: Yes, SINGLETON: No
pub const OPTION_DHCPV4_MSG: OptionCode = 87;	// [RFC7341], ORO: No, SINGLETON: Yes
pub const OPTION_DHCP4_O_DHCP6_SERVER: OptionCode = 88;	// [RFC7341], ORO: Yes, SINGLETON: Yes
pub const OPTION_S46_RULE: OptionCode = 89;	// [RFC7598], ORO: No, SINGLETON: No[2]
pub const OPTION_S46_BR: OptionCode = 90;	// [RFC7598][RFC8539], ORO: Yes, SINGLETON: No
pub const OPTION_S46_DMR: OptionCode = 91;	// [RFC7598], ORO: No, SINGLETON: Yes
pub const OPTION_S46_V4V6BIND: OptionCode = 92;	// [RFC7598], ORO: No, SINGLETON: Yes
pub const OPTION_S46_PORTPARAMS: OptionCode = 93;	// [RFC7598], ORO: No, SINGLETON: Yes
pub const OPTION_S46_CONT_MAPE: OptionCode = 94;	// [RFC7598], ORO: Yes, SINGLETON: No
pub const OPTION_S46_CONT_MAPT: OptionCode = 95;	// [RFC7598], ORO: Yes, SINGLETON: Yes
pub const OPTION_S46_CONT_LW: OptionCode = 96;	// [RFC7598], ORO: Yes, SINGLETON: Yes
pub const OPTION_4RD: OptionCode = 97;	// [RFC7600], ORO: Yes, SINGLETON: Yes
pub const OPTION_4RD_MAP_RULE: OptionCode = 98;	// [RFC7600], ORO: Yes, SINGLETON: Yes
pub const OPTION_4RD_NON_MAP_RULE: OptionCode = 99;	// [RFC7600], ORO: Yes, SINGLETON: Yes
pub const OPTION_LQ_BASE_TIME: OptionCode = 100;	// [RFC7653], ORO: No, SINGLETON: Yes
pub const OPTION_LQ_START_TIME: OptionCode = 101;	// [RFC7653], ORO: No, SINGLETON: Yes
pub const OPTION_LQ_END_TIME: OptionCode = 102;	// [RFC7653], ORO: No, SINGLETON: Yes
pub const DHCP_CAPTIVE_PORTAL: OptionCode = 103;	// [RFC7710], ORO: Yes, SINGLETON: Yes
pub const OPTION_MPL_PARAMETERS: OptionCode = 104;	// [RFC7774], ORO: Yes, SINGLETON: No
pub const OPTION_ANI_ATT: OptionCode = 105;	// [RFC7839], ORO: No, SINGLETON: Yes
pub const OPTION_ANI_NETWORK_NAME: OptionCode = 106;	// [RFC7839], ORO: No, SINGLETON: Yes
pub const OPTION_ANI_AP_NAME: OptionCode = 107;	// [RFC7839], ORO: No, SINGLETON: Yes
pub const OPTION_ANI_AP_BSSID: OptionCode = 108;	// [RFC7839], ORO: No, SINGLETON: Yes
pub const OPTION_ANI_OPERATOR_ID: OptionCode = 109;	// [RFC7839], ORO: No, SINGLETON: Yes
pub const OPTION_ANI_OPERATOR_REALM: OptionCode = 110;	// [RFC7839], ORO: No, SINGLETON: Yes
pub const OPTION_S46_PRIORITY: OptionCode = 111;	// [RFC8026], ORO: Yes, SINGLETON: Yes
pub const OPTION_MUD_URL_V6: OptionCode = 112;	// [RFC8520], ORO: No, SINGLETON: Yes
pub const OPTION_V6_PREFIX64: OptionCode = 113;	// [RFC8115], ORO: Yes, SINGLETON: No
pub const OPTION_F_BINDING_STATUS: OptionCode = 114;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_CONNECT_FLAGS: OptionCode = 115;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_DNS_REMOVAL_INFO: OptionCode = 116;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_DNS_HOST_NAME: OptionCode = 117;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_DNS_ZONE_NAME: OptionCode = 118;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_DNS_FLAGS: OptionCode = 119;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_EXPIRATION_TIME: OptionCode = 120;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_MAX_UNACKED_BNDUPD: OptionCode = 121;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_MCLT: OptionCode = 122;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_PARTNER_LIFETIME: OptionCode = 123;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_PARTNER_LIFETIME_SENT: OptionCode = 124;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_PARTNER_DOWN_TIME: OptionCode = 125;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_PARTNER_RAW_CLT_TIME: OptionCode = 126;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_PROTOCOL_VERSION: OptionCode = 127;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_KEEPALIVE_TIME: OptionCode = 128;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_RECONFIGURE_DATA: OptionCode = 129;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_RELATIONSHIP_NAME: OptionCode = 130;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_SERVER_FLAGS: OptionCode = 131;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_SERVER_STATE: OptionCode = 132;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_START_TIME_OF_STATE: OptionCode = 133;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_F_STATE_EXPIRATION_TIME: OptionCode = 134;	// [RFC8156], ORO: No, SINGLETON: Yes
pub const OPTION_RELAY_PORT: OptionCode = 135;	// [RFC8357], ORO: No, SINGLETON: Yes
pub const OPTION_V6_SZTP_REDIRECT: OptionCode = 136;	// [RFC8572], ORO: Yes, SINGLETON: Yes
pub const OPTION_S46_BIND_IPV6_PREFIX: OptionCode = 137;	// [RFC8539], ORO: Yes, SINGLETON: Yes
pub const OPTION_IPV6_ADDRESS_ANDSF: OptionCode = 143;	// [RFC6153], ORO: Yes, SINGLETON: Yes

pub fn to_str(a: OptionCode) -> Result<&'static str, ()> {
  match a {
    1 => Ok("OPTION_CLIENTID"),
    2 => Ok("OPTION_SERVERID"),
    3 => Ok("OPTION_IA_NA"),
    4 => Ok("OPTION_IA_TA"),
    5 => Ok("OPTION_IAADDR"),
    6 => Ok("OPTION_ORO"),
    7 => Ok("OPTION_PREFERENCE"),
    8 => Ok("OPTION_ELAPSED_TIME"),
    9 => Ok("OPTION_RELAY_MSG"),
    11 => Ok("OPTION_AUTH"),
    12 => Ok("OPTION_UNICAST"),
    13 => Ok("OPTION_STATUS_CODE"),
    14 => Ok("OPTION_RAPID_COMMIT"),
    15 => Ok("OPTION_USER_CLASS"),
    16 => Ok("OPTION_VENDOR_CLASS"),
    17 => Ok("OPTION_VENDOR_OPTS"),
    18 => Ok("OPTION_INTERFACE_ID"),
    19 => Ok("OPTION_RECONF_MSG"),
    20 => Ok("OPTION_RECONF_ACCEPT"),
    21 => Ok("OPTION_SIP_SERVER_D"),
    22 => Ok("OPTION_SIP_SERVER_A"),
    23 => Ok("OPTION_DNS_SERVERS"),
    24 => Ok("OPTION_DOMAIN_LIST"),
    25 => Ok("OPTION_IA_PD"),
    26 => Ok("OPTION_IAPREFIX"),
    27 => Ok("OPTION_NIS_SERVERS"),
    28 => Ok("OPTION_NISP_SERVERS"),
    29 => Ok("OPTION_NIS_DOMAIN_NAME"),
    30 => Ok("OPTION_NISP_DOMAIN_NAME"),
    31 => Ok("OPTION_SNTP_SERVERS"),
    32 => Ok("OPTION_INFORMATION_REFRESH_TIME"),
    33 => Ok("OPTION_BCMCS_SERVER_D"),
    34 => Ok("OPTION_BCMCS_SERVER_A"),
    36 => Ok("OPTION_GEOCONF_CIVIC"),
    37 => Ok("OPTION_REMOTE_ID"),
    38 => Ok("OPTION_SUBSCRIBER_ID"),
    39 => Ok("OPTION_CLIENT_FQDN"),
    40 => Ok("OPTION_PANA_AGENT"),
    41 => Ok("OPTION_NEW_POSIX_TIMEZONE"),
    42 => Ok("OPTION_NEW_TZDB_TIMEZONE"),
    43 => Ok("OPTION_ERO"),
    44 => Ok("OPTION_LQ_QUERY"),
    45 => Ok("OPTION_CLIENT_DATA"),
    46 => Ok("OPTION_CLT_TIME"),
    47 => Ok("OPTION_LQ_RELAY_DATA"),
    48 => Ok("OPTION_LQ_CLIENT_LINK"),
    49 => Ok("OPTION_MIP6_HNIDF"),
    50 => Ok("OPTION_MIP6_VDINF"),
    51 => Ok("OPTION_V6_LOST"),
    52 => Ok("OPTION_CAPWAP_AC_V6"),
    53 => Ok("OPTION_RELAY_ID"),
    54 => Ok("OPTION_IPV6_ADDRESS_MOS"),
    55 => Ok("OPTION_IPV6_FQDN_MOS"),
    56 => Ok("OPTION_NTP_SERVER"),
    57 => Ok("OPTION_V6_ACCESS_DOMAIN"),
    58 => Ok("OPTION_SIP_UA_CS_LIST"),
    59 => Ok("OPT_BOOTFILE_URL"),
    60 => Ok("OPT_BOOTFILE_PARAM"),
    61 => Ok("OPTION_CLIENT_ARCH_TYPE"),
    62 => Ok("OPTION_NII"),
    63 => Ok("OPTION_GEOLOCATION"),
    64 => Ok("OPTION_AFTR_NAME"),
    65 => Ok("OPTION_ERP_LOCAL_DOMAIN_NAME"),
    66 => Ok("OPTION_RSOO"),
    67 => Ok("OPTION_PD_EXCLUDE"),
    68 => Ok("OPTION_VSS"),
    69 => Ok("OPTION_MIP6_IDINF"),
    70 => Ok("OPTION_MIP6_UDINF"),
    71 => Ok("OPTION_MIP6_HNP"),
    72 => Ok("OPTION_MIP6_HAA"),
    73 => Ok("OPTION_MIP6_HAF"),
    74 => Ok("OPTION_RDNSS_SELECTION"),
    75 => Ok("OPTION_KRB_PRINCIPAL_NAME"),
    76 => Ok("OPTION_KRB_REALM_NAME"),
    77 => Ok("OPTION_KRB_DEFAULT_REALM_NAME"),
    78 => Ok("OPTION_KRB_KDC"),
    79 => Ok("OPTION_CLIENT_LINKLAYER_ADDR"),
    80 => Ok("OPTION_LINK_ADDRESS"),
    81 => Ok("OPTION_RADIUS"),
    82 => Ok("OPTION_SOL_MAX_RT"),
    83 => Ok("OPTION_INF_MAX_RT"),
    84 => Ok("OPTION_ADDRSEL"),
    85 => Ok("OPTION_ADDRSEL_TABLE"),
    86 => Ok("OPTION_V6_PCP_SERVER"),
    87 => Ok("OPTION_DHCPV4_MSG"),
    88 => Ok("OPTION_DHCP4_O_DHCP6_SERVER"),
    89 => Ok("OPTION_S46_RULE"),
    90 => Ok("OPTION_S46_BR"),
    91 => Ok("OPTION_S46_DMR"),
    92 => Ok("OPTION_S46_V4V6BIND"),
    93 => Ok("OPTION_S46_PORTPARAMS"),
    94 => Ok("OPTION_S46_CONT_MAPE"),
    95 => Ok("OPTION_S46_CONT_MAPT"),
    96 => Ok("OPTION_S46_CONT_LW"),
    97 => Ok("OPTION_4RD"),
    98 => Ok("OPTION_4RD_MAP_RULE"),
    99 => Ok("OPTION_4RD_NON_MAP_RULE"),
    100 => Ok("OPTION_LQ_BASE_TIME"),
    101 => Ok("OPTION_LQ_START_TIME"),
    102 => Ok("OPTION_LQ_END_TIME"),
    103 => Ok("DHCP_CAPTIVE_PORTAL"),
    104 => Ok("OPTION_MPL_PARAMETERS"),
    105 => Ok("OPTION_ANI_ATT"),
    106 => Ok("OPTION_ANI_NETWORK_NAME"),
    107 => Ok("OPTION_ANI_AP_NAME"),
    108 => Ok("OPTION_ANI_AP_BSSID"),
    109 => Ok("OPTION_ANI_OPERATOR_ID"),
    110 => Ok("OPTION_ANI_OPERATOR_REALM"),
    111 => Ok("OPTION_S46_PRIORITY"),
    112 => Ok("OPTION_MUD_URL_V6"),
    113 => Ok("OPTION_V6_PREFIX64"),
    114 => Ok("OPTION_F_BINDING_STATUS"),
    115 => Ok("OPTION_F_CONNECT_FLAGS"),
    116 => Ok("OPTION_F_DNS_REMOVAL_INFO"),
    117 => Ok("OPTION_F_DNS_HOST_NAME"),
    118 => Ok("OPTION_F_DNS_ZONE_NAME"),
    119 => Ok("OPTION_F_DNS_FLAGS"),
    120 => Ok("OPTION_F_EXPIRATION_TIME"),
    121 => Ok("OPTION_F_MAX_UNACKED_BNDUPD"),
    122 => Ok("OPTION_F_MCLT"),
    123 => Ok("OPTION_F_PARTNER_LIFETIME"),
    124 => Ok("OPTION_F_PARTNER_LIFETIME_SENT"),
    125 => Ok("OPTION_F_PARTNER_DOWN_TIME"),
    126 => Ok("OPTION_F_PARTNER_RAW_CLT_TIME"),
    127 => Ok("OPTION_F_PROTOCOL_VERSION"),
    128 => Ok("OPTION_F_KEEPALIVE_TIME"),
    129 => Ok("OPTION_F_RECONFIGURE_DATA"),
    130 => Ok("OPTION_F_RELATIONSHIP_NAME"),
    131 => Ok("OPTION_F_SERVER_FLAGS"),
    132 => Ok("OPTION_F_SERVER_STATE"),
    133 => Ok("OPTION_F_START_TIME_OF_STATE"),
    134 => Ok("OPTION_F_STATE_EXPIRATION_TIME"),
    135 => Ok("OPTION_RELAY_PORT"),
    136 => Ok("OPTION_V6_SZTP_REDIRECT"),
    137 => Ok("OPTION_S46_BIND_IPV6_PREFIX"),
    143 => Ok("OPTION_IPV6_ADDRESS_ANDSF"),
    _ => Err(()),
  }
}
